### ISSUE TITLE
Before/After Change Event Type for updateConfiguration

### ISSUE THREAD

**Issue by ssriniva123** [Netflix/archaius#133]
Folks,
I have a ConfigurationListener which gets events from the zookeepersource.
Any node change triggers two events , however the value for both the events
is set to the changes value(the before change event also has the new value).

I got two events , the name of zode is host and new value is 'test'.
I got two hits with same value.

System.out.println("Got configurationChanged  = " + arg0.isBeforeUpdate() + ":"+ arg0.getPropertyName() + ":" + arg0.getPropertyValue());

Got configurationChanged  = true:host:test
Got configurationChanged  = false:host:test

I am using 

<dependency>
  <groupId>com.netflix.archaius</groupId>
  <artifactId>archaius-core</artifactId>
  <version>0.5.5</version>
 </dependency>
 
              
<dependency>
	<groupId>com.netflix.archaius</groupId>
	<artifactId>archaius-zookeeper</artifactId>
	<version>0.5.11</version>
</dependency>

**Comment by howardyuan** [comment]
Closing this issue for now since we don't use archaius-zookeeper here internally at Netflix. If somebody else reports the issue or submits a fix, we'll update the issue.
