### ISSUE TITLE
Why doesn't URLConfigurationSource use ConfigurationUtils.getPropertiesFromFile?

### ISSUE THREAD

**Issue by jakber** [Netflix/archaius#137]
Currently it seems to me like you cannot use the `@next` special property in files referenced by the default `DynamicURLConfiguration`. So out of the box you cannot load cascaded configurations dynamically from URLs, right? Any particular reason for this? 

Would you be open to a pull request where instead of loading properties from URLs in the `poll` method it calls `ConfigurationUtils.getPropertiesFromFile` to do the loading as well as handling `@next`?

**Comment by fiddleatwork** [comment]
I ran into this same issue, that is I would like to have dynamic cascaded configuration files.  Is there any news on this issue?  I see the previous poster submitted a NamedConfigurationSource, has anyone used it?

**Comment by howardyuan** [comment]
In Netflix, the URLConfigurationSource is another REST endpoint. So adding cascading obviously doesn't make sense here. It has been pretty quiet on this thread over the years.
