### ISSUE TITLE
Support Typesafe Config

### ISSUE THREAD

**Issue by fernandezpablo85** [Netflix/archaius#148]
Is there any way (or will be) to read configuration values from Typesafe Config[1]?

If not, are you willing to accept a patch? should it be a different artifact?

BTW I'm asking this here since I couldn't find a mailing list for the project and @netflixOSS (Twitter) was unresponsive.

[1] http://github.com/typesafehub/config

**Comment by fernandezpablo85** [comment]
is this ever going to happen?

**Comment by howardyuan** [comment]
@fernandezpablo85 The PR was merged way back? You didn't see it?

**Comment by fernandezpablo85** [comment]
seems I missed it, I was using a fork. will close this issue and go back to the oficial release. thanks.
