### ISSUE TITLE
Refactor properties for easier unit testing

### ISSUE THREAD

**Issue by tnine** [Netflix/archaius#149]
We need to unit test several of our dynamic configuration updates.  This currently requires a lot of code to create unit tests.  Please add the ability to either subclass a property, or create a method to directly inject a new value to trigger the listeners.

I.E

DynamicIntProperty testProp = new DynamicIntProperty("test", 5);

//test code

testProp.setValue(2);

//listeners fire

//test code

**Comment by howardyuan** [comment]
Closing this issue for now since Archaius V2 should solve the static nature of DP of Archaius V1
