### ISSUE TITLE
AbstractPollingScheduler not sharable?

### ISSUE THREAD

**Issue by siggimoo** [Netflix/archaius#154]
Wandering through the source, I noticed the checkpoint used in polling sources is held as an instance variable of AbstractPollingScheduler. This would seem to suggest that a single scheduler instance cannot be shared across sources as their checkpoints might conflict if polled at the same time. Is this the case? Should I be using one scheduler per source even if the characteristics are identical?

**Comment by howardyuan** [comment]
Closing this issue for now since we're focusing on Archaius V2 now.
