### ISSUE TITLE
Allow for re-installation of a custom configuration

### ISSUE THREAD

**Issue by seppyk** [Netflix/archaius#155]
This is an improvement request.

Currently, one can create a custom configuration and install it via the ConfigurationManager:

```
ConfigurationManager.install(abstractConfiguration);
```
One cannot re-install a configuration due to the check in DynamicPropertyFactory

```
if (ConfigurationManager.isConfigurationInstalled() && config != ConfigurationManager.instance) {
  throw new IllegalStateException("ConfigurationManager is already initialized with configuration " + ConfigurationManager.getConfigInstance());
}
```
It would be useful to be able to re-define the installed configuration dynamically.   This also causes some conflicts in a Spring test environment as the application context can reload during testing with a different configuration that can never be re-installed.

**Comment by chandrapersonal** [comment]
Any updates on this. re-install a configuration should be feasible. i am useing ETCD as source in archaius  to dynamically update the properties in spring. but my etcd server  connection is timeing out for 5 min. So i have to re-install configuration source. Is there any other way to configure ETCD more than one time.

**Comment by howardyuan** [comment]
@chandrapersonal Can you clarify your problem? Are you saying that your etcd source is no longer available and you want to use a different source? If so, I think you should be able to create a new polling source instead of re-install the configuration manager as the #113 issue was referring to.
