### ISSUE TITLE
DynamicStringProperty does not interpolate variables on update

### ISSUE THREAD

**Issue by jbaiera** [Netflix/archaius#198]
Ran some tests with this recently to verify some assumptions. Glad that I did. Here's my testing code and properties: 

```java
public class ArchaiusTest {
	public static final String KEY = "test.message";
	public static final String DEFAULT = "No Message Found";

	public static void main(String[] args) throws Exception 
	{
		DynamicStringProperty message
				= DynamicPropertyFactory.getInstance().getStringProperty(KEY, DEFAULT);

		Configuration configuration = ConfigurationManager.getConfigInstance();

		while (true)
		{
			System.out.println("dynamic : " + message.get());
			System.out.println("config  : " + configuration.getString(KEY, DEFAULT));
			TimeUnit.SECONDS.sleep(30);
		}
	}
}
```

And the properties file that I'm using : 
```properties
message.default=default
message.new=new

test.message=This is the ${message.default} message
```

If I launch the process, the two outputs are the same. If I change the `message.default` property to be something else (lets say "old"), the dynamic property will remain as "default", but the Configuration object will correctly update the variable interpolation to use "old" in the place holder.

Also, if I completely change the variable (lets say to `message.new`) the dynamic property picks up the raw, un-interpolated variable name, but the configuration object correctly interpolates the value.

I've posted the program output. *\*Text surrounded by asterisks are my interactions with the environment\**

> \* Start Program \*
> 
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> dynamic : This is the default message
> config  : This is the default message
> 
> \* Update configuration - 'message.default=old' \*
> 
> dynamic : This is the default message
> config  : This is the default message
> dynamic : This is the default message
> config  : This is the default message
>
> \* Program picks up updated configuration \*
> 
> dynamic : This is the default message
> config  : This is the old message
> dynamic : This is the default message
> config  : This is the old message
> 
> \* Update configuration - 'test.message=This is the ${message.new} message' \*
> 
> dynamic : This is the default message
> config  : This is the old message
> dynamic : This is the default message
> config  : This is the old message
> 
> \* Program picks up updated configuration \*
> 
> dynamic : This is the ${message.new} message
> config  : This is the new message
> 
> \* Kill Program \*
> 
> Process finished with exit code 137

Is this expected behavior?

**Comment by howardyuan** [comment]
Closing this for now since there's been no traction for a while now.
