### ISSUE TITLE
Inconsistent behavior on initial property load vs property update when escaping characters with "\"

### ISSUE THREAD

**Issue by siminwang** [Netflix/archaius#208]
Using Archaius-Core 0.6.0. 

I'm trying to store and load a regex in zookeeper into Archaius and I've found my regex property to return unexpected values based on if the property was loaded on startup, or set during runtime.

If I have this string in ZK: "[^/\\#?]{0,1024}"

Initial load and retrieval of the property produces : "[^/\#?]{0,1024}" (missing \)
However, after of which, if i set the property to the exact same original value and trigger an update. The property comes back as the original literal string.

I can see and understand the need for interpreting escape characters but due to the inconsistent behavior it makes real time updates to the property fail on restart of the application.

**Comment by howardyuan** [comment]
The code paths for the initial load and update are indeed different. We're trying to focus on Archaius V2 now which will be different in initial load. Closing this issue for now since most likely we won't fix the Archaius V1 for this.
