### ISSUE TITLE
Release 0.6.4

### ISSUE THREAD

**Issue by nightwolfzor** [Netflix/archaius#210]
Hey guys, looks like 0.6.4 didn't release properly to OSS staging; https://oss.sonatype.org/content/repositories/staging/com/netflix/archaius/archaius-typesafe/0.6.4/ 

Getting a 404 :(

**Comment by howardyuan** [comment]
The release process didn't go through. Looking into recovery steps now.

**Comment by howardyuan** [comment]
The best way to recover is to release again. The only problem is we lost 0.6.4 along the way. Please use 0.6.5 instead.

**Comment by nightwolfzor** [comment]
Thanks!
