### ISSUE TITLE
Typo in com.netflix.config.ConfigurationBasedDeploymentContext

### ISSUE THREAD

**Issue by tnaroska** [Netflix/archaius#211]
com.netflix.config.ConfigurationBasedDeploymentContext overwrites deployment.stack with value from deployment.serverId.

Typo is in here:
https://github.com/Netflix/archaius/commit/4cf06fb02346da0a11822d06dc8f7206a94b5cd6#diff-5d700d06a18011241a4d491359d3d70bR132

**Comment by howardyuan** [comment]
Do you mind providing a PR for this?

**Comment by tnaroska** [comment]
https://github.com/Netflix/archaius/pull/214
