### ISSUE TITLE
Guava classpath issues

### ISSUE THREAD

**Issue by jsmodic** [Netflix/archaius#212]
Archaius depends on a pretty old version of Guava (looks like 11.0.2 in build.gradle).

In 16.0, Guava removed Closeables#closeQuietly(...) which is used at least once here.

So it causes any other application to have NoSuchMethod errors if they're trying to use a newer version of Guava in the application with Archaius.

**Comment by howardyuan** [comment]
Do you mind providing a PR to change the closeQuietly to close(closeable, true)? Netflix internally is still using 14.0 or 15.0 so this hasn't bitten us yet.

**Comment by jsmodic** [comment]
Sure. I'll set one up soon.
