### ISSUE TITLE
Build times out in Jenkins

### ISSUE THREAD

**Issue by gorzell** [Netflix/archaius#228]
The build seems to be taking longer than 20 min on a build worker, which seem to be the max jenkins is configured for.  We should either configure the build job with a longer timeout or remove some of the build steps (i.e. Cobertura instrumentation).

ref: https://netflixoss.ci.cloudbees.com/job/archaius-master/71

**Comment by brharrington** [comment]
@gorzell  The build was running on a pretty tiny machine. I changed the build to restrict to label hi-speed and the last run took 4 min 54 sec (https://netflixoss.ci.cloudbees.com/job/archaius-master/72/). So at least it should be unblocked for now.
