### ISSUE TITLE
2.x questions

### ISSUE THREAD

**Issue by brharrington** [Netflix/archaius#263]
Looking at AbstractConfig:

1. Does getBoolean really need 3 different ways to say "true"?
2. getInteger and friends will currently return null if the value cannot be parsed and the NumberFormatException is swallowed. This seems like something the user should be made aware of as it is either a bug in the code using the config or in the configuration.
3. What is the overall philosophy around errors? For example, looking at TypesafeConfig and MapConfig one will throw and exception if getRawProperty is called with a missing value and the other will return null.

**Comment by brharrington** [comment]
How is property file loading supposed to work for a library? For the code I could depend on core, but if I provide a reference.conf with the library for use with typesafe config, it won't get loaded unless the end user happens to choose the typesafe binding. The flexibility with different bindings makes it hard to know what I can count on being supported and working for the end user.

**Comment by elandau** [comment]
1.  This is mostly for backward compatibility
2.  Agreed, these should all throw exceptions
3.  All getXXX(String key) methods should throw a not found exception.

**Comment by elandau** [comment]
Any call to addConfigFirst/Last on AppConfig will load the config into the library layer.  You should be able to load the entire typesafe configuration and add it by calling addConfigFirst.

```java
appConfig.addConfig(new TypesafeConfig("name", ConfigFactory.load()));
```
