### ISSUE TITLE
any possibility to implement push.

### ISSUE THREAD

**Issue by AdoHe** [Netflix/archaius#283]
LGTM.

**Comment by elandau** [comment]
@AdoHe I don't understand what you asking for here?  Can you please provide more information about what it is you are asking for.

**Comment by AdoHe** [comment]
@elandau I mean archaius now use poll to fetch configuration information from source, any possibility to implement push?

**Comment by howardyuan** [comment]
For now, we don't have immediate plan to implement push. We'll re-visit this when we see more needs for it.
