### ISSUE TITLE
update commons-configuration

### ISSUE THREAD

**Issue by jpcaruana** [Netflix/archaius#298]
Apache commons-configuration has been released in 2013-10-27 with version 1.10 (Minor bug fixes and improvements). Why does archaius still use the outdated version 1.8 from 2012-02-04 ? (I ran `gradlew test` with this version, and everything worked fine.)

see https://commons.apache.org/proper/commons-configuration/changes-report.html#a1.10 for changelog

Thanks

**Comment by howardyuan** [comment]
@jpcaruana We'll look into upgrading commons-configuration. In the meantime, Achaius 2.0 is trying to be totally independent of common-configuration. Please check it out if you're interested in a much lighter Archaius.

**Comment by jpcaruana** [comment]
thanks for the insight @howardyuan 
in fact I use archaius via hystrix, not directly (for now)
