### ISSUE TITLE
Change instance variable of DynamicPropertyFactory to Holder class

### ISSUE THREAD

**Issue by drosowski** [Netflix/archaius#319]
Hi,
mocking the DynamicPropertyFactory in unit tests is problematic, because it gets instantiated as a static field. Using a static inner class holding the instance would be a more test-friendly alternative.
This approach would still guarantee a singleton and you could get rid of the double check in getInstance() as well.
Maybe I will create a pull request if I can find the time.

Cheers,
Daniel

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
