### ISSUE TITLE
2.x ConfigurationProxy required properties

### ISSUE THREAD

**Issue by elandau** [Netflix/archaius#336]
It would be nice to have a mechanism to indicate that a configuration value is required.

Two possible approaches 
1.  If no @DefaultValue (regardless of primitive type or not) then fail if value not found (preferred)
2.  New @RequiredValue annotation to indicate that a value is required.

For example,

@Configuration(prefix="foo")
public interface ServerConfiguration {
   Integer serverPort();
}

If the property 'foo.serverPort' does not exist then it would be easy to log a detailed message with the specific configuration that's missing.

**Comment by brharrington** [comment]
I prefer option 1. 

How are empty values currently handled? Would I have to set a default to `@DefaultValue(null)` or something similar?

**Comment by elandau** [comment]
Yes, you would explicitly have to specify the default value of null or ""

**Comment by gorzell** [comment]
I am not exactly sure what you are trying to get at.  The current behavior is that if you call get() without a default you will get an exception.  Which I think is ideal/correct.  Is this separate from that?

**Comment by elandau** [comment]
This change is specific to definition configuration using proxied interfaces (note the Config interface).  The current behavior is to return null for non-primitives.
