### ISSUE TITLE
don't know eough scala to fix compile problem with: ChainedLongProperty & ChainedStringProperty

### ISSUE THREAD

**Issue by autohandle** [Netflix/archaius#338]
Download https://jcenter.bintray.com/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedBooleanProperty.scala:21: error: in class ChainedBooleanProperty, multiple overloaded alternatives of constructor ChainedBooleanProperty define default arguments.
[ant:scalac] class ChainedBooleanProperty(
[ant:scalac]       ^
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedFloatProperty.scala:22: error: in class ChainedFloatProperty, multiple overloaded alternatives of constructor ChainedFloatProperty define default arguments.
[ant:scalac] class ChainedFloatProperty(
[ant:scalac]       ^
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedIntProperty.scala:22: error: in class ChainedIntProperty, multiple overloaded alternatives of constructor ChainedIntProperty define default arguments.
[ant:scalac] class ChainedIntProperty(
[ant:scalac]       ^
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedLongProperty.scala:22: error: in class ChainedLongProperty, multiple overloaded alternatives of constructor ChainedLongProperty define default arguments.
[ant:scalac] class ChainedLongProperty(
[ant:scalac]       ^
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedProperty.scala:62: warning: method propertyNames in class MapChainBy does nothing other than call itself recursively
[ant:scalac]     override def propertyNames: Iterable[String] = propertyNames
[ant:scalac]                                                    ^
[ant:scalac] /Volumes/Users/david/Documents/eclipse/netflix/archaius/archaius-scala/src/main/scala/com/netflix/config/scala/ChainedStringProperty.scala:22: error: in class ChainedStringProperty, multiple overloaded alternatives of constructor ChainedStringProperty define default arguments.
[ant:scalac] class ChainedStringProperty(
[ant:scalac]       ^
[ant:scalac] one warning found
[ant:scalac] 5 errors found
:archaius-scala:compileScala FAILED

this link is trying to tell me what to do:
https://www.chrisstucchio.com/blog/2014/multiple_overloaded_alternatives.html
but, i'm not smart enough to figure it out.

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
