### ISSUE TITLE
double checking lock in DynamicProperty.java

### ISSUE THREAD

**Issue by gopircr** [Netflix/archaius#362]
The following method is from class DynamicProperty.java.  
Double-check lock may not always work. In certain situations,  when multiple threads are updating and reading the data, property value may be lost temporarily and may result in reading null value.

``` java
public T getValue() throws IllegalArgumentException {
            // Not quite double-check locking -- since isCached is marked as volatile
            if (!isCached) {
                synchronized (lock) {
                    System.out.println("In Lock Method");
                    try {
                        value = (stringValue == null) ? null : parse(stringValue);
                        exception = null;
                    } catch (Exception e) {
                        value = null;
                        exception = new IllegalArgumentException(e);
                    } finally {
                        isCached = true;
                    }
                }
            }
            if (exception != null) {
                throw exception;
            } else {
                return value;
            }
        }
```

``` java
boolean updateValue(Object newValue) {
        String nv = (newValue == null) ? null : newValue.toString();
        synchronized (lock) {
            if ((nv == null && stringValue == null)
               || (nv != null && nv.equals(stringValue))) {
                return false;
            }
            stringValue = nv;
            cachedStringValue.flush();

           /*   if (!"test".equals(stringValue)) {
                    sleepNow(2000);
                    System.out.println("flushed and now sleeping...");

                }*/


            booleanValue.flush();
            integerValue.flush();
            floatValue.flush();
            classValue.flush();
            doubleValue.flush();
            longValue.flush();
            changedTime = System.currentTimeMillis();
            return true;
        }
    }
```

Here is the sequence when getValue() can return a null:

1) Thread 1 checks isCached as true and get past the first if condition in getValue Method without going into the synchronized block

2) Context switch to thread 2.   Thread 2 runs flush() in updateValue Method.  At this point, cached value is reset to Null.

3) Thread 1 resumes.   Now it returns an empty value.

I was able to reproduce this issue by forcing context switching of threads by adding Thread.sleep in a few places.

**Comment by howardyuan** [comment]
@gopircr Thanks for catching this one. I'm surprised that it's only brought up now. Let's think about best solution together. We really don't want to introduce any overhead to getValue(). At this point, I'm leaning toward in updateValue(), we don't flush and change isCached status. Instead, simply update the values for all the cachedValue objects. getValue() may get some old values if another thread is updating at the same time, but it's at least eventual consistent instead of returning null.

**Comment by gopircr** [comment]
I agree with you that we should not be introducing any overhead in the getValue().   Your solution seems pretty good and will satisfy 99.9% of the use cases where eventual consistency is tolerated.

**Comment by howardyuan** [comment]
Fix should be available in next release.
