### ISSUE TITLE
Archaius 0.7.2 not found in maven central nor bintray

### ISSUE THREAD

**Issue by jaume-pinyol** [Netflix/archaius#363]
Hi,

Where do you upload your libraries, karyon 2.7.4 uses archaius-core:0.7.2 but I'm not able to find it.
I could compile it myself but maybe someone else will have the same issue. 
The last version in maven central is 0.7.1 so I've forced it in my app build.gradle.

Thanks!
Jaume Pinyol

**Comment by brharrington** [comment]
Not sure about maven central, but it is in the bintray jcenter repo:

http://jcenter.bintray.com/com/netflix/archaius/archaius-core/0.7.2/

**Comment by jaume-pinyol** [comment]
Thanks for your help!! I actually didn't check there, I checked the bintray frontend and it wasn't there so I though it wasn't in the repo. I've solved the issue ;) 

Closing the issue
