### ISSUE TITLE
PolledConfigurationSource Implementation

### ISSUE THREAD

**Issue by sarginm** [Netflix/archaius#375]
It would be great if I get some help in consul polling.I am using Abstract Polling Scheduler and once the poling is started , it is polling the source for 5 to 6 times and suspending the thread.

AbstractPollingScheduler scheduler = new FixedDelayPollingScheduler();
      scheduler.startPolling(consulConfigurationSource, myConfiguration);

Do we have to do install our custom configuration to the Configuration manager. 
Please suggest , to run the thread  as long running daemon. Thanks in Advance.

**Comment by howardyuan** [comment]
Without the context and code, it's hard to know exactly what went wrong. What do you mean by "polling the source for 5 to 6 times and suspending the thread"?

**Comment by sarginm** [comment]
Sorry for the limited information.
I am trying to Poll Consul KV store to update my configuration file. I have implemented the polling using FixedDelayPollingScheduler. Here is  the code snippet.

public class ConsulConfigurationSource implements PolledConfigurationSource {

	ConsulClient client = new ConsulClient("127.0.0.1");
	KeyValueConsulClient keyvalueclient = new KeyValueConsulClient();
	
	public ConsulConfigurationSource(KeyValueConsulClient keyvalueclient) {
		this.keyvalueclient = keyvalueclient;
		
	}
	
	/**
     * Create a full result that represents the complete content of the configuration source.
     * @param  map that contains all the properties
     */	
	@Override
	public PollResult poll(boolean initial, Object checkPoint) throws Exception {
		//Thread.sleep(200);		
	Map<String, Object> map = load();	
	return PollResult.createFull(map);	
	}
	synchronized Map<String, Object> load() throws Exception {		
		QueryParams queryParams = new QueryParams("dc1");
		Response<List<GetValue>> valuesList = keyvalueclient.getKVValues("", queryParams);
		Map<String, Object> map = new HashMap<>();		
		
		for (GetValue item : valuesList.getValue()){
		     
		     String Kvalue = item.getValue();
		     String Key = item.getKey();
		     map.put(item.getKey().replace('/', '.'), getDecoded(Kvalue));
		  }	
		
		return map;
	}


}


Here, I am Initialising the Scheduler:

ConsulConfigurationSource source = new ConsulConfigurationSource(keyvalueclient);
AbstractPollingScheduler scheduler = new FixedDelayPollingScheduler(0, 10, false);
DynamicConfiguration configuration = new DynamicConfiguration(source, scheduler);
DynamicPropertyFactory.initWithConfigurationSource(configuration);


The above code, starts the polling and continuing around 30 to 35 times then automatically stops the polling.I could not find any time limitation in the scheduler.
Please help me to understand, why the polling fails.
Thanks in Advance.

**Comment by howardyuan** [comment]
I couldn't think of any reason why you will stop by itself? How do you know it did 30 to 35 times? How do know it stops polling? Is that your main thread exiting that's causing this?

**Comment by howardyuan** [comment]
I meant the polling thread stoping by itself.

**Comment by sarginm** [comment]
I had added a counter variable to check the number of times , the poll method is being invoked. After these random number of times,  the scheduler is calling stop() method, which stops the poll execution.
And Yes, the main thread is also getting terminated.

**Comment by howardyuan** [comment]
So you put a break point in stop(), can you figure out the stack trace and who initiated the stop()? I think this is outside of Archaius, but you should be able to debug it and figure it out for sure.

**Comment by sarginm** [comment]
I just went through the stack trace and found the archaius-core/src/main/java/com/netflix/config/DynamicConfiguration.java  class is calling stopLoading() method, which in turn calls the scheduler stop() method.
Thanks for your time.
