### ISSUE TITLE
Maven dependencies are runtime instead of compile

### ISSUE THREAD

**Issue by spencergibb** [Netflix/archaius#379]
This changed after 0.6.5 (see pom [here](http://search.maven.org/#artifactdetails%7Ccom.netflix.archaius%7Carchaius-core%7C0.6.5%7Cjar).

http://search.maven.org/#artifactdetails%7Ccom.netflix.archaius%7Carchaius-core%7C0.7.3%7Cjar

I remember seeing this on another project. I think it was the update to the new build system cf73e123f7ea38a229501c194acd79cdc4138f16.

**Comment by brharrington** [comment]
For reference, here are some previous discussions on this for other projects: https://github.com/ReactiveX/RxNetty/issues/292, https://github.com/Netflix/ribbon/issues/206

**Comment by spencergibb** [comment]
Also https://github.com/Netflix/Hystrix/issues/730 and their solution https://github.com/Netflix/Hystrix/pull/944

**Comment by spencergibb** [comment]
`commons-configuration` is a compile dependency.

**Comment by spencergibb** [comment]
I'm a bit confused, marked closed and tagged with enhancement/v1?

**Comment by howardyuan** [comment]
The change is already in place. The labels were added just for clarification purpose.

**Comment by spencergibb** [comment]
@howardyuan what version is the change in?

**Comment by howardyuan** [comment]
@spencergibb Sorry, I misread the issue and thought you're saying 0.6.5 has the issue. Let me follow up with other teams and see how we want to proceed with this since this same issue happens with other projects as well.

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
