### ISSUE TITLE
Cannot Read Files using archaius.configurationSource.additionalUrls

### ISSUE THREAD

**Issue by rajkumar1979** [Netflix/archaius#419]
I am trying to leverage on Archaius for dynamic loading of property files.

I am trying to access properties defined in the project class path and also on the system class path.

When I try to test the code, the files from the system class path are not getting loaded.

I wanted to specify a list of files that need to be read from the system classpath.

I am trying to test this in my spring project.

 @Before
    public void setup() {
        ConfigurationManager.getConfigInstance().setProperty("archaius.deployment.environment","dev");
        ConfigurationManager.getConfigInstance().
   setProperty("archaius.configurationSource.additionalUrls","file:///Users/rramakrishnan/innovation/innovation-third.properties");

```
}
```

Appreciate any help on this.

Thanks

Raj.

**Comment by kornkreismuster** [comment]
You got a slash too much within your Url.
IMHO you need to configure "file://Users/rramakrishnan/innovation/innovation-third.properties"

I made the same mistake and it took me hours...
