### ISSUE TITLE
How does archaius keep track of all the property files

### ISSUE THREAD

**Issue by rajkumar1979** [Netflix/archaius#420]
Want to understand how does archaius keep track of all the property files.

What feature does it use to poll and update the changes ? how often does it poll?

And which API in Archaius polls for the changes and keeps updating the properties?

Appreciate your help in understanding this?

Thanks

**Comment by howardyuan** [comment]
Can you go through the Wiki pages first and hopefully you will have more targeted questions? Your current questions are too general.
