### ISSUE TITLE
infinite loop?

### ISSUE THREAD

**Issue by mebigfatguy** [Netflix/archaius#423]
In ChainedProperty.scala, i see

  protected[this] class MapChainBy[B, TYPE](unmappedBox: ChainBox[TYPE, _], fn: %28TYPE%29 => B, mapType: Manifest[B])
  extends ChainedProperty[B]
  {
    override protected val box = new ChainBoxConverter[B, TYPE](unmappedBox, fn, mapType)

```
override def propertyNames: Iterable[String] = propertyNames
```

  }

i'm not sure what's going on here, but it looks to me like
propertyNames() is going to be an infinite recursive loop.

**Comment by howardyuan** [comment]
@mebigfatguy I don't know much about the archaius-scala module. Is this a real issue?

**Comment by mebigfatguy** [comment]
Was it found in the wild? no.

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
