### ISSUE TITLE
Question : Why can't I override default properties once set in config.properties ?

### ISSUE THREAD

**Issue by alainkr** [Netflix/archaius#424]
Hello,
I'm using hystrix. When I configure `config.properties` on the classpath with the property set to 1234 than setting the prop like below fails 

```java
@Test
 public void should_change_confiprop_default() {
 String key = "hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds";
 assertEquals("1234",String.valueOf(ConfigurationManager.getConfigInstance().getProperty(key)));
 ConfigurationManager.getConfigInstance().setProperty(key,"5678");
 assertEquals("5678",String.valueOf(ConfigurationManager.getConfigInstance().getProperty(key)));  //fails :-(
 }
 
```

It's seams that when doing `ConfigurationManager.getConfigInstance().getProperty(key)` it will retreive the property for the first source having the key.

```java
 Snippet from com.netflix.config.ConcurrentCompositeConfiguration.getProperty(String)
  public Object getProperty(String key)
    {
        if (overrideProperties.containsKey(key)) {
            return overrideProperties.getProperty(key);
        }
        Configuration firstMatchingConfiguration = null;
        for (Configuration config : configList)
        {
            if (config.containsKey(key))
            {
                firstMatchingConfiguration = config;
                break;
            }
        }


        if (firstMatchingConfiguration != null)
        {
            return firstMatchingConfiguration.getProperty(key);
        }
        else
        {
            return null;
        }
    }
```

confList is : [org.apache.commons.configuration.SystemConfiguration@7fc229ab, com.netflix.config.DynamicURLConfiguration@2cbb3d47, com.netflix.config.ConcurrentMapConfiguration@527e5409]

The config.properties looks like to be loaded in the DynamicURLConfiguration [value 1234] while when i'm setting the property it happens in the last one : ConcurrentMapConfiguration [value 5678]

So the getproperty will always be returned from the DynamicURLConfiguration. 

I don't see how I can change this behavior.

Thanks for your help.

**Comment by howardyuan** [comment]
DynamicURLConfiguration takes precedence over the setProperty() in configuration layers. However, if you really want to override DynamicURLConfiguration, you can use setOverrideProperty(). But remember if you want to be able to change configuration without pushing code, you don't want to override the DynamicURLConfiguration in your code.

**Comment by alainkr** [comment]
Sorry but I don't get it. I have a config.properties file for some basic default for hystrix.
Now we 'd like a rest service to momentarily change the configuration on the fly.

How would I code that ? 
I tought  
```
ConfigurationManager.getConfigInstance().setProperty(key,value);
``` 
Would do. but it doesn't when using config.properties. If I don't use config.properties it has the behavior I except. What am I missing ? Thanks.

**Comment by howardyuan** [comment]
ConfigurationManager.getConfigInstance().setProperty(key,value); only changes the property in local configuration. But REST service is not part of Archaius. I think you configure DynamicURLConfiguration to point to config.properties? And DynamicURLConfiguration takes precedence over setProperty(). That's why your config.properties always shows up. You can write a simple REST service to host your config.proeprties and point DynamicURLConfiguration to that REST service. That should give you what you want.
