### ISSUE TITLE
Does archaius now support sending only property changes only during polling?

### ISSUE THREAD

**Issue by billyy** [Netflix/archaius#425]

**Comment by howardyuan** [comment]
Are you asking if the property changes are updated through push or poll? Currently, it's through polling at the polling interval.

**Comment by billyy** [comment]
No.  My question is about if archaius can poll only the properties that
have been changed.  For example, if I have 100 properties and only 3
changes, archaius will only get 3 new values at the next polling interval
instead of all 100.

Thanks

**Comment by howardyuan** [comment]
I see. Currently, no. Current polling configuration source will get everything to the client side and then find out difference between the current client state and polled results, then only publish those differences into the configuration. This is to distribute the load between server and client and make server stateless.
