### ISSUE TITLE
Any plans to implement a archaius2-aws?

### ISSUE THREAD

**Issue by dimiro1** [Netflix/archaius#428]
Any plans to implement a archaius2-aws?

**Comment by gorzell** [comment]
It probably wouldn't be that hard to port over, it is a very simple implementation.  Because it is simple it does run into problems if you want to do layering or overrides with it.

**Comment by rgallardo-netflix** [comment]
The team does not currently have the resources to try this. If you are interested in trying to do it, I believe that the archaius2-persisted2 module would be a good starting point.
