### ISSUE TITLE
Get properties used by application

### ISSUE THREAD

**Issue by Aloren** [Netflix/archaius#434]
I would like to get all properties that are used by application.
For example in my configuration db I have:

```
property1=value1
property2=value2
property3=value3
property4=value4
```

and my application uses only `property1` and `property3` properties. I would like to have some kind of registry in which all actually used properties were held (in my case it would hold: `property1`,`property3`).
I have looked through the code, but haven't found something like that. As I understand the starting point for implementation of such feature is `DynamicProperty` class. Correct me if I am wrong. 
Thanks.

**Comment by howardyuan** [comment]
Can you elaborate a bit more on your use case and context? Tracking property usage is indeed useful. However, it can be tricky. For one, many users don't use DynamicProperty to get the properties. Instead, they access the properties through configurations directly. If you plan to use the registry for further actions like removing properties, there can be consequences. Another thing I worry about is that now you're tagging everybody with some extra overhead even if they don't care for the usages. This is actually a big topic so we need to give it more thoughts.

**Comment by Aloren** [comment]
> Can you elaborate a bit more on your use case and context?

In our application there are a lot of libraries that fetch settings in different ways. Sometimes it becomes really difficult to track which settings are actually used by application. 

> many users don't use DynamicProperty to get the properties. Instead, they access the properties through configurations directly.

Ok, I understand. Maybe there is another point where I can surely know that setting was requested by application?

> Another thing I worry about is that now you're tagging everybody with some extra overhead

This feature can be optional, by default it will be off.

**Comment by howardyuan** [comment]
@Aloren Tracking the usage at per property level is a big change. At this point, we don't plan to implement it in Archaius 1. But we'll look into this in Archaius 2 and later versions.
