### ISSUE TITLE
Multiple configuration through additionalUrls

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/archaius#441]
@howardyuan 

I am supplying the configuration through the additionalUrls argument. I am supplying a url of a config hosted on s3. Is there any way I can specify more than one url, as a fallback. Because while debugging I just deleted S3 file and found out that archaius doesn't pick the config.properties on the classpath. So is it written this way itself or is there a workaround?

**Comment by howardyuan** [comment]
You need to have a composite config. This composite config (in your case) has two layers. One is config.properties, the other (taking precedence over the first layer) is your s3 configuration source.
