### ISSUE TITLE
DynamicPropertyUpdater: ClassCastException bug on line 134

### ISSUE THREAD

**Issue by darekmydlarz** [Netflix/archaius#448]
Hey, there is a bug in `DynamicPropertyUdpater:134`: https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/DynamicPropertyUpdater.java#L134

When `newValue` is not a String, but for instance `Integer` it throws `ClassCastException`

**Comment by howardyuan** [comment]
@dmydlarz do you have a special use case for a non-string valued property? From the code itself, it definitely will throw exception as you said. But Archaius itself has an assumption that the root property value is always string (follow Java properties convention).

**Comment by ViktorStolbovoy** [comment]
I had the same issue. It was caused by "blah: false" property in bootstrap.yml config file.

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
