### ISSUE TITLE
Archaius 2: Default implementations of collection properties in config interface are ignored

### ISSUE THREAD

**Issue by Helmsdown** [Netflix/archaius#454]
Given the following config interface and my.app.prefix.setOfStrings1 is _not_ specified in a config file, myCustomConfig.getSetOfStrings1() returns an empty LinkedHashSet.

``` java
@Configuration(prefix = "my.app.prefix.")
public interface MyCustomConfig {
    default Set<String> getSetOfStrings1() {
        return Sets.newHashSet("value1", "value2");
    }
}
```

I am using archaius2-core-2.1.7

**Comment by elandau** [comment]
Fixed with #492
