### ISSUE TITLE
Loading cascading properties in Archaius

### ISSUE THREAD

**Issue by mukteshkrmishra** [Netflix/archaius#456]
HI,

How can we load cascading (series) of properties using Archaius. In my project I have different property files say A, B, C, D. Which are containing some properties. I want to load all of those property files using Archaius (One way to load is using @Next as key in property file).

But for second property file how will it get loaded, by putting @next again (PS, I am assuming that since key is same, thus only on property file will be loaded per global context. (ie: at a time only one @next value will be picked up).

Is it true? Can anybody please explain.

**Comment by howardyuan** [comment]
@mukteshkrmishra For example, if you want to the overriding sequence to be D>C>B>A (D will override C and C will override B, etc.), then you can add "@next=B,C,D" at the last line of your A property file. Archaius will load A, then B, then C, then D.
