### ISSUE TITLE
Web UI and CLI for Archaius (& soon Eureka) with FF4j

### ISSUE THREAD

**Issue by clun** [Netflix/archaius#462]
First, I would like to **thank you** for the material you provided to the community, NetFlix OSS rocks ! This "issue" is neither a bug report nor a pull request. This is for communication / awareness and maybe to get some feedbacks on the work I did.

### FF4j

**[FF4j ](ff4j.org)** is a proposition of framework to implement **Feature Toggle** pattern in Java.
- You can enable and disable features at runtime through provided clients and consoles (Web, CLI, JMX).
- You can persist the features states in different technologies like *JDBC, Redis, Mongo, Neo4j, Cassandra, Elastic, JCache*, EhCache...*
- Features have not only a status (true/false) but can be enabled for dedicated users *(Canary release)* or/and have a custom strategy *(Pattern Strategy)* 
- You have metrics of the usage of your features.

<img src="http://ff4j.org/wiki/console-1.6-features.jpg" /> 
<img src="http://ff4j.org/wiki/console-1.6-monitoring.png" /> 

### Properties
We noticed pretty soon that "features states" are very closed from properties (at the end of the day they are "only" properties of boolean type). Yet, they are not used in the same way and this is the reason why we created aside the "PropertyStore" interface to implement CRUD operations on properties. In the same way as FeatureStore we also provided UI and clients.

<img src="http://ff4j.org/archiaus/ff4j-archiaus-edit.png" /> 

### Archaius and Commons configuration

For version 1.6.x we implement wrappers & bridges to combine CommonsConfiguration/FF4J and Archaius.

#### Use the FF4J properties as a source for Commons-configuration
You already has set up your application to use commons configurations but feel limited as the existing `Configuration`  are limited to properties and xml files. Use the `FF4jConfiguration` to inject properties coming from other sources. [sample code](https://github.com/clun/ff4j/blob/master/ff4j-archaius/src/test/java/org/ff4j/commonsconf/CommonsConfigWithPropertyStoreTest.java)
<img src="http://ff4j.org/archiaus/ff4j-as-source-for-commons-config.png" width="400px"/> 
 
#### Use the FF4J properties as a source for Archaius 
Sample principle as before. Archaius leverage on commons configuration and provides new sources for properties. You can use the `FF4JConfiguration` and add FF4J properties to the dynamic configuration. Archiaus also introduce the `PolledSourceConfiguration` mechanism to polled target properties provider and update configuration accordingly. The `ff4j-archaius` module propose and implementation of `PolledSourceConfiguration` to work with FF4J. [sample code](https://github.com/clun/ff4j/blob/master/ff4j-archaius/src/test/java/org/ff4j/archaius/PropertyStoreArchaiusPolledSourceTest.java)
<img src="http://ff4j.org/archiaus/ff4j-as-source-for-archiaus.png" width="400px"/> 

*Objective* : You can now use Archiaus with properties coming from : JDBC, Redis, Mongo, Neo4j, Cassandra, Elastic, JCache*, EhCache*

#### Use Commons Config for FF4J property store
If properties are defined in a ff4j  `PropertyStore`, they will be available in the web UI and CLI. AS a consequence you can perform CRUD operations through UI (caution some stores are read-only). [sample code](https://github.com/clun/ff4j/blob/master/ff4j-archaius/src/test/java/org/ff4j/commonsconf/PropertyStoreCommonsConfigTest.java)
<img src="http://ff4j.org/archiaus/commons-config-as-ff4j-source.png" width="400px"/> 

### Use Archiaus for FF4J property store
Sample principle as before with Archaius, define a `PropertyStore` to work with a dynamic configuration, you will get all properties values in the UI. [sample code](https://github.com/clun/ff4j/blob/master/ff4j-archaius/src/test/java/org/ff4j/archaius/PropertyStoreArchaiusPolledSourceTest.java)
<img src="http://ff4j.org/archiaus/archiaus-as-source-for-ff4j.png" width="400px"/> 

Objective:
- You will have a  CLI to edit and display properties.
<img src="http://ff4j.org/archiaus/ff4j-cli.png" width="400px"/> 

- You will have a dedicated WebUI to see properties, and edit them.
<img src="http://ff4j.org/archiaus/ff4j-archaius-home.png" /> 

As a working sample is always better than documentation or long text you can test it yourself [here](https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-archaius):

Let me know if you find this useful, well any feedbacks are welcomed.

*NB: Next version of ff4j will provide the `FeatureStore` and `PropertyStore` to work with directly with Eureka.*

**Comment by mblasi** [comment]
It would be really interesting tool! Is this WIP?

**Comment by clun** [comment]
it's ready and working. Please find here a working sample:
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-archaius

FF4J is about 10k download per month from Central and I was surprised with the "no reaction" effect of this entry. Any feedbacks are more than welcomed.

**Comment by mblasi** [comment]
I'm testing it right now! I'll back with my feedback and questions. Thank you very much!

**Comment by clun** [comment]
It's working as expected, test it if you wish, I can close this issue
