### ISSUE TITLE
Possible issues w/ PropertyWrapper?

### ISSUE THREAD

**Issue by pkwarren** [Netflix/archaius#468]
When looking at the implementation of PropertyWrapper, I've seen two potential issues for consumers of this API:

* `PropertyWrapper` wraps a `DynamicProperty` (which is thread safe), but appears to not be thread safe itself (specifically the `callbackList` field). It would be useful to document this (that `addCallback` and `removeAllCallbacks` should be synchronized) or perhaps switch the `callbackList` to a `CopyOnWriteArrayList` similar to `DynamicProperty`. Reference: https://github.com/Netflix/archaius/blob/e623c0131bdfa4a06a9cf62c2c2bc0a2e31f3ff7/archaius-core/src/main/java/com/netflix/config/PropertyWrapper.java#L41
* In `removeAllCallbacks`, the callback is removed from `DynamicProperty` but the entry in `callbackList` is not removed. This will lead to a resource leak over time as there doesn't appear to be a way to remove callbacks from `callbackList`. Reference: https://github.com/Netflix/archaius/blob/e623c0131bdfa4a06a9cf62c2c2bc0a2e31f3ff7/archaius-core/src/main/java/com/netflix/config/PropertyWrapper.java#L156-L164

I can raise a PR to resolve these issues.

**Comment by howardyuan** [comment]
@pkwarren Sure, please raise a PR so we can look at it together. Thanks.

**Comment by pkwarren** [comment]
@howardyuan - Opened #470 with a proposed fix for these issues.

**Comment by pkwarren** [comment]
@howardyuan - Have you had a chance to look at this PR?

**Comment by rgallardo-netflix** [comment]
won't fix: v1 has been deprecated
