### ISSUE TITLE
Support values across multiple lines

### ISSUE THREAD

**Issue by mattnelson** [Netflix/archaius#477]
I am trying to use the multiline support[1] from commons-config. When loading the configuration[2] through the provided example[3] the output[4] demonstrates that the multiline values are not honored. Is this feature supported with archaius?

[1] http://commons.apache.org/proper/commons-configuration/javadocs/v1.10/apidocs/org/apache/commons/configuration/PropertiesConfiguration.html

[2]
```properties
multivaluekey=one,two,three
multilinekey=one
multilinekey=two
multilinekey=three
```
[3]
```java
@Test
public void multiValueConfig() throws ConfigurationException {
    AbstractConfiguration configInstance = ConfigurationManager.getConfigInstance();
    System.out.println("archaius multiline key");
    System.out.println(configInstance.getList("multilinekey"));
    System.out.println(Arrays.asList(configInstance.getStringArray("multilinekey")));
    System.out.println("archaius multivalue key");
    System.out.println(configInstance.getList("multivaluekey"));
    System.out.println(Arrays.asList(configInstance.getStringArray("multivaluekey")));
    
    PropertiesConfiguration propertiesConfiguration = new PropertiesConfiguration("config.properties");
    System.out.println("commons config multiline key");
    System.out.println(propertiesConfiguration.getList("multilinekey"));
    System.out.println(Arrays.asList(propertiesConfiguration.getStringArray("multilinekey")));
    System.out.println("commons config multivalue key");
    System.out.println(propertiesConfiguration.getList("multivaluekey"));
    System.out.println(Arrays.asList(propertiesConfiguration.getStringArray("multivaluekey")));
}
```
[4]
```
archaius multiline key
[three]
[three]
archaius multivalue key
[one, two, three]
[one, two, three]
commons config multiline key
[one, two, three]
[one, two, three]
commons config multivalue key
[one, two, three]
[one, two, three]
```

**Comment by howardyuan** [comment]
@mattnelson Archaius doesn't support multiline key. The complexity of supporting this across all layers of Archaius outweighs the benefit imo.

**Comment by mattnelson** [comment]
Is there documentation on the features where archaius breaks compatibility with commons-config? The configuration manager returns an instance of the commons-config interface so the assumption would be that the implementation is compliant with the interface.

https://github.com/Netflix/archaius/blob/v0.7.5/archaius-core/src/main/java/com/netflix/config/ConfigurationManager.java#L179

**Comment by mattnelson** [comment]
Took a stab at implementing this for configuration url sources only. Please consider accepting this change. Turned out to a pretty strait forward implementation.
