### ISSUE TITLE
No way to disable configuration polling

### ISSUE THREAD

**Issue by dmak** [Netflix/archaius#485]
This is not a big deal, however `FixedDelayPollingScheduler` always creates a separate thread for polling if the configuration file  changes even in the case this is not necessary. For example if configuration file is located in the classpath and is packaged with application there is no need to poll it. This is just a waste of resources. To keep things simpler, I suggest to add an extra check into `DynamicURLConfiguration` constructor:
```java
if (source.getConfigUrls() != null && source.getConfigUrls().size() > 0 && FixedDelayPollingScheduler.isPollingEnabled()) {
    startPolling(source, new FixedDelayPollingScheduler());
}
```
and in `FixedDelayPollingScheduler`:
```java
public static boolean isPollingEnabled() {
    // Special value "-1" of the given system property means "disable polling":
    return Integer.getInteger(DELAY_PROPERTY, 0) != -1;
}
```

**Comment by rgallardo-netflix** [comment]
V1 is no longer being maintained.
