### ISSUE TITLE
Memory leak when using DynamicStringMapProperty

### ISSUE THREAD

**Issue by sachinmaheshwari** [Netflix/archaius#487]
I have 5 Map properties configured in config.properties file which are about 500-1000 characters long. After running server for few hours I can see around 50k instances of DynamicStringMapProperty all having same values and all of them (I checked it randomly) having some root reference hence its not getting garbage collected. It's further holding multiple instances of concurrent hash map and all the strings. Which gradually builds up and leads to out of memory error.

Please check this screenshot it was taken after full GC. (jmap live dump)

![screen shot 2017-05-09 at 11 39 22 am](https://cloud.githubusercontent.com/assets/10795268/25837613/4492f212-34ac-11e7-9236-3b828e294647.png)

I'm accessing this Map using this code.
`return new DynamicStringMapProperty("map-key-name", new HashMap<>()).getMap();`

This code is called from a method that finishes very quickly and its not holding the reference of this map after method is over.

**Comment by brharrington** [comment]
My guess is that it is because you are creating many instances of `DynamicStringMapProperty`. Typically you would create one instance and reuse it.

https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/DynamicPropertyFactory.java#L26

**Comment by sachinmaheshwari** [comment]
That's exactly what I'm trying now. I noticed that for every instance it is creating a callback handler which is never collected by GC. Hence that could be the reason. 
I have deployed one fix on my servers which is using only one instance. I will update my findings here.

**Comment by sachinmaheshwari** [comment]
And that works no more memory leak. Thank you. 

Closing the issue.
