### ISSUE TITLE
make commons-configuration optional

### ISSUE THREAD

**Issue by adriancole** [Netflix/archaius#52]
I'd like to be able to employ archaius without pulling in commons configuration and its dependencies:  https://commons.apache.org/configuration/dependencies.html

For example, in jclouds we only use guice and rocoto.  I'd like to be able to have the dynamic equivalent of Names, for example, and I don't think it is necessary to route through commons-config to write a plugin like this:

http://google-guice.googlecode.com/svn/trunk/javadoc/com/google/inject/name/Names.htm

**Comment by jpcaruana** [comment]
updated link to javadoc: http://google.github.io/guice/api-docs/3.0/javadoc/com/google/inject/name/Names.html
