### ISSUE TITLE
Property value update callback event is not execute for cascading property

### ISSUE THREAD

**Issue by patashish** [Netflix/archaius#527]
Dear Team,

Property value update event is not fired for cascading property files.
For example , I have 2 property files.
1) firstfile.proprties
firstkey1=firstvalue1
@next=firstfile-${myenv}.proprties

1) firstfile-dev.proprties
secondkey1=secondvalue2
@next=third.properties

**Sample Source code to print the value :** 

Class Main{
static {
		System.setProperty("archaius.configurationSource.defaultFileName", "firstfile.properties");
		try {
			ConfigurationManager.loadCascadedPropertiesFromResources("firstfile");
		} catch (IOException e) {			
			e.printStackTrace();
		}
	}
final  DynamicStringProperty firstkey1DynamicStringProperty = DynamicPropertyFactory.getInstance().getStringProperty("firstkey1","defaultValue", new Runnable() {
			public void run() {
				System.out.println("********* firstkey1 PROP UPDATE EVENT************************");
			}
		});
final  DynamicStringProperty secondkey1DynamicStringProperty = DynamicPropertyFactory.getInstance().getStringProperty("secondkey1","defaultValue", new Runnable() {
		public void run() {
			System.out.println("********* secondkey1 PROP UPDATE VENT****************************");
				}
	});
} .....

// Note : This program is running in thread and key value is printed correct from both prop file.

When i change any value in firstfile.property file, callback event is executed.
But When i change any value in firstfile-dev.property file, callback event is not executed. i.e. After changing the value of secondkey1 , its callback method is not called hence updated value is not captured.

Please suggest.

**Comment by huseyinocal035** [comment]
You have to  add the line
spring.profiles.active=dev 
in your firstfile.proprties. Then callback event will be executed. Otherwise, just read firstfile.proprties file.
