### ISSUE TITLE
archaius-core uses duplicated slf4j-api dependency

### ISSUE THREAD

**Issue by jCalamari** [Netflix/archaius#545]
Hi, I was checking dependencies on hystrix-core and found out archaius uses two (?) slf4j-api implementations. This is not a major one, just flagging this up. The graph was generated by sbt dependency graph plugin.

<img width="674" alt="screen shot 2018-04-02 at 20 36 14" src="https://user-images.githubusercontent.com/9678999/38212521-eb3e2404-36b5-11e8-9648-5beb91f3d6d8.png">

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
