### ISSUE TITLE
get operation on dynamic property returning child data

### ISSUE THREAD

**Issue by vinayvakati** [Netflix/archaius#560]
new DynamicStringListProperty("testprop", new ArrayList<>()).get() returning 

[ChildData{path=<actual path>, stat=4294969976, 4295050172, 1535439839508, 1536035879078, 1, 0, 0, 0, 3, 0, 4294969976, data=[65, 69, 93]}]

**Comment by rgallardo-netflix** [comment]
v1 is no longer maintained
