### ISSUE TITLE
DynamicListProperty with `,` as delimitter returns `[` & `]`

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/archaius#569]
Given a property with a comma separated value such as
myTestProperty=a,b,c

Reading these values using the DynamicListPropertyValue results in values as shown below
sample code:
```
List<String> myTestPropertyValues = new DynamicStringListProperty("myTestProperty", "").get()
``` 

The resulting values in the list are: `[ "[a", "b", "c]" ]`
When the expected outcome should be `[ "a", "b", "c" ]`

**Comment by rgallardo-netflix** [comment]
v1 is no longer maintained
