### ISSUE TITLE
Allow Configuration Source Updates

### ISSUE THREAD

**Issue by mpaauw** [Netflix/archaius#616]
Due to the issues raised in [this](https://github.com/Netflix/archaius/issues/46) discussion, it makes sense to allow the underlying property source to be modified or refreshed after it has already been initialized. Not allowing modification in the underlying source results in convoluted test setups, which can add both [complexity and unnecessary execution time](https://github.com/Netflix/archaius/issues/46#issuecomment-28715958) when requiring each test to run in a separate JVM in order to be able to change the underlying config source. 

Simply giving `public` access to the `DynamicProperty.updateProperty` and `DynamicProperty.updateAllProperties` here should be sufficient.

**Comment by rgallardo-netflix** [comment]
V1 is no longer maintained.
