### ISSUE TITLE
Question: why invoke the callback method of  properies like this " r.run() ，and are there othe reseaons？

### ISSUE THREAD

**Issue by yuzhongzhu** [Netflix/archaius#625]
DynamicProperty#notifyCallbacks
for (Runnable r : callbacks) {
            try {
                r.run();
            } catch (Exception e) {
                logger.error("Error in DynamicProperty callback", e);
            }
        }

**Comment by rgallardo-netflix** [comment]
This seems to be more of a general Java question.
