### ISSUE TITLE
Add support for returning collections in parameterized properties

### ISSUE THREAD

**Issue by akang31** [Netflix/archaius#681]
While normal properties support returning collections via the ConfigProxyFactory, parameterized properties do not.

e.g.
```
@Configuration
interface Foo {
  @PropertyName(name = "foo.bar.${0}")
  Set<String> getFooBarSet(String s);
}
```

**Comment by rgallardo-netflix** [comment]
I've single-stepped through this and I think the issue is rooted in ConfigProxyFactory#L322, where the propertyValueGetter for a parametrized property is built. We are passing in the raw list type, we need to pass the parametrized type instead.
