### ISSUE TITLE
young gc long time and Out-of-heap memory leak

### ISSUE THREAD

**Issue by xianfengxiong** [Netflix/archaius#727]
archaius-core: 0.6.6 
version : 0.6.6

when i use spring-cloud-starter-openfeign:2.0.2.RELEASE, 
found young gc take a long time, and slow out-of-heap memory leak!

![image](https://github.com/Netflix/archaius/assets/16450036/6b259aed-874e-4d61-94d9-68e9e3162865)

analyse dump file, fund the Inflater object too many
OQL: SELECT classof(f.referent).@name FROM java.lang.ref.Finalizer f WHERE (f.referent != null)

![image](https://github.com/Netflix/archaius/assets/16450036/f7b1dbc1-5812-4f46-93e6-26f083231221)

use jmap -histo 1 | grep 'Inflater', fund this object slow increase
![image](https://github.com/Netflix/archaius/assets/16450036/0210537b-1e27-4a20-a05a-c53809e80d7e)

at last, i foud the cause is "pollingConfigurationSource" ScheduledThreadPool execute task every 60 seconds,
the task is URLConfigurationSource.poll(), the task will invoke url.openStream() method, the url is config.properties file by default, url.openStream() will new Inflater object.

I didn't know I was using it wrong or a bug ?

**Comment by rgallardo-netflix** [comment]
You are using very old versions of archaius (and of spring-cloud-starter-openfeign, for that matter). Archaius 1 is deprecated and we will not be fixing any hard-to-reproduce bugs such as this one. If you have a simpler test case we *may* consider a fix.
