### ISSUE TITLE
Feature Request: Custom deserialization

### ISSUE THREAD

**Issue by cheddar** [Netflix/archaius#87]
Config can often be grouped together rather than splatted out.  

Things like DropWizard show some great examples of where combining config into a YAML/JSON object can make things a bit nicer to work with.  It would be great if there were a DynamicProperty type that essentially allowed the caller to specify their own deserialization logic such that they could convert "complex" objects into Java config objects.

As it is, I have something similar to archaius setup around storing JSON payloads in a DB.  I convert them from the JSON payload into a Java object with Jackson and use that java object as a config object in my code.  I'd like to swap in archaius, but I cannot without having to deserialize a string property over and over and over again (or add some complexity with an AtomicReference<> and using the callbacks to deserialize into it).

If I could essentially register my own deserialization archaius and have it such that it would only deserialize into the Java object that I care about when the value changes, that'd be awesome.

**Comment by howardyuan** [comment]
Closing the issue for now since there has been no traction on this for a while now.

**Comment by vijayparashar12** [comment]
it's 2017 doesn't it make sense to have YAML file support for configurations. supporting only ".properties" doesn't make much sense to me.

**Comment by tgmuender** [comment]
I would definitely also welcome YAML support. Could be something for version 2?
