### ISSUE TITLE
Dynamic property is not working with local configuration files

### ISSUE THREAD

**Issue by lokee103** [Netflix/archaius#92]
Having the following program when changes are made for a property in the prop file doesn't seem to be reflected in the value.

``` java
static DynamicLongProperty dynamicLongProperty = DynamicPropertyFactory.getInstance().getLongProperty("a.property", 1010101);

    public static void main(String[] args) throws MalformedURLException, InterruptedException {

        String url = new File("D:\\prop.properties").toURI().toURL().toString();

        DynamicURLConfiguration dynamicURLConfiguration = new DynamicURLConfiguration(10000, 10000, false,
                url);
        ConcurrentMapConfiguration configFromPropertiesFile = new ConcurrentMapConfiguration(dynamicURLConfiguration);

        ConcurrentCompositeConfiguration finalConfig = new ConcurrentCompositeConfiguration();
        finalConfig.addConfiguration(configFromPropertiesFile, "fileConfig");

        ConfigurationManager.install(finalConfig);

        while (true) {
            System.out.println("++++" + dynamicLongProperty.get());
            Thread.sleep(5000);
        }
    }
```

I can see that when I update the property it gets read by archaius but the value won't change in the sys out:

++++444
11:58:48.954 [pollingConfigurationSource] DEBUG c.n.config.AbstractPollingScheduler - Polling started
11:58:48.954 [pollingConfigurationSource] DEBUG c.n.config.DynamicPropertyUpdater - updating property key [a.property], value [333]
++++444

**Comment by abhishekmahawar** [comment]
Hi, I'm facing  a similar issue while directly getting a property from default config file. Following is the code snippet :

package com.autodesk.archaius;

import com.netflix.config.*;

public class TestArchaius {

    public static void main (String[] args) throws InterruptedException {
        System.setProperty("archaius.dynamicPropertyFactory.registerConfigWithJMX", "true");
        System.setProperty("archaius.fixedDelayPollingScheduler.initialDelayMills", "1");
        System.setProperty("archaius.fixedDelayPollingScheduler.delayMills", "100");

        DynamicLongProperty timeToWait = DynamicPropertyFactory.getInstance().getLongProperty("lock.waitTime", 1000);
        while (true) {
            System.out.println("++++" + timeToWait.get());
            Thread.sleep(5000);
        }
        //ConcurrentCompositeConfiguration config = (ConcurrentCompositeConfiguration)DynamicPropertyFactory.getBackingConfigurationSource();
        //config.setOverrideProperty("lock.waitTime", 500);
    }
}

I do get the updated property if I update it via JMX bean or using the backing config source. Can you please point me to the issue here ? I've my default config.properties in the classpath of project.

**Comment by Aithosa** [comment]
> it's not working probably because you used ide to modify config file, you don't know when ide really write change to file and save. try to open config file with other software as windows notebook or notepad, change the config value and save the file, you may see the code print the latesed config value after setting time
