### ISSUE TITLE
Using Dynamo DB for Deployment Context with archaius

### ISSUE THREAD

**Issue by hardeepparmar** [Netflix/archaius#93]
I would like to know what typically would be the Dynamo DB table structure for using deployment context based properties...For e.g
I have a uniqued ID is "id" as primary key  in a dynamoDB table and then I want to have different values for attributes say a1, a2 , a3, a4...for each deployment context.
My deployment context can say have values "test", "prod", "stage" ...

As i understand the Dynamo DB should look something like this...

ID    deploymentContext     a1     a2    a3     a4

===============================================

1     "test"                        t11    t12   t13     t14
2     "stage"                     s11    s12  s13    s14
3     "prod"                       p11    p12   p13   p14

Here ID would be primary key and deploymentContext  would be the range key and the code(as i understand) should look something like this

ArrayList<AttributeDefinition> attributeDefinitions = new ArrayList<AttributeDefinition>();

attributeDefinitions.add(new AttributeDefinition().withAttributeName("ID").withAttributeType(ScalarAttributeType.S));
			attributeDefinitions.add(new AttributeDefinition().withAttributeName("deploymentContext" ).withAttributeType(ScalarAttributeType.S));
			
			KeySchemaElement key= new KeySchemaElement().withAttributeName(keyAttributeName.get()).withKeyType(KeyType.HASH);
			KeySchemaElement range= new KeySchemaElement().withAttributeName(contextKeyAttributeName.get()).withKeyType(KeyType.RANGE);
			
			ArrayList<KeySchemaElement> ks= new ArrayList<KeySchemaElement>();
			ks.add(key);
			ks.add(range);
			
CreateTableRequest req = new CreateTableRequest().withTableName(tableName.get()).withKeySchema(ks).withProvisionedThroughput(output);
req.setAttributeDefinitions(attributeDefinitions);
dbClientForCreatingTable.createTable(req);

... And then code to populate  a1     a2    a3     a4 in the table.

However when i use archaius to load such a  table it throws an exception in DynamoDbDeploymentContextTableCache::loadPropertiesFromTable at line 255 while deciphering the value of enum from contextKeyAttributeName.get()).getS() where contextKeyAttributeName.get()).getS()  is getting evaluated to either "test", "prod" or stage e.t.c depending on value stored in DynamoDB.

May i know what is going wrong with my assumptions regrading how archaius uses dynamoDb vis a vis deployment context.

**Comment by howardyuan** [comment]
Closing this for now since there has been traction on it.
